/**
 * js/data.js - 全球与国内热点原始数据集 (12世界 + 12国内)
 */
window.HOTSPOT_DATA = {
  world: [
    {
      id: 'w001',
      title: '联合国气候峰会达成新减排协议',
      category: 'policy',
      city: '伦敦, 英国',
      lat: 51.5074,
      lng: -0.1278,
      heat: 982,
      level: 'major',
      sentiment: 'positive',
      spread: 12800000,
      summary: '多国代表在伦敦峰会上就2035年非化石能源比重达成历史性共识，将建立多边绿色转型基金。'
    },
    {
      id: 'w002',
      title: '全球半导体供应链峰会发布新规',
      category: 'tech',
      city: '圣何塞, 美国',
      lat: 37.3382,
      lng: -121.8863,
      heat: 945,
      level: 'critical',
      sentiment: 'neutral',
      spread: 15200000,
      summary: '半导体厂商联合声明优化先进制程产能调配，应对国际物流及原材料波动。'
    },
    {
      id: 'w003',
      title: '欧佩克宣布维持原油产量配额',
      category: 'economy',
      city: '维也纳, 奥地利',
      lat: 48.2082,
      lng: 16.3738,
      heat: 890,
      level: 'major',
      sentiment: 'neutral',
      spread: 9400000,
      summary: '石油输出国组织及盟友决定暂不调整现行日均产量，国际油价盘中窄幅震荡。'
    },
    {
      id: 'w004',
      title: '东京湾海底火山轻微活动预警解除',
      category: 'emergency',
      city: '东京, 日本',
      lat: 35.6762,
      lng: 139.6503,
      heat: 865,
      level: 'normal',
      sentiment: 'positive',
      spread: 7100000,
      summary: '日本气象厅监测表明海底震颤已恢复基线水平，海啸预警正式取消。'
    },
    {
      id: 'w005',
      title: '欧洲央行维持主要再融资利率不变',
      category: 'economy',
      city: '法兰克福, 德国',
      lat: 50.1109,
      lng: 8.6821,
      heat: 812,
      level: 'major',
      sentiment: 'neutral',
      spread: 8100000,
      summary: '通胀数据持续向2%目标靠拢，央行官员表态未来利率路径将取决于核心数据。'
    },
    {
      id: 'w006',
      title: '新一代开源量子计算模拟器发布',
      category: 'tech',
      city: '苏黎世, 瑞士',
      lat: 47.3769,
      lng: 8.5417,
      heat: 780,
      level: 'normal',
      sentiment: 'positive',
      spread: 6500000,
      summary: '苏黎世联邦理工学院团队开源百万量子比特级多体物理模拟框架，引发学术界热议。'
    },
    {
      id: 'w007',
      title: '南极冰架裂隙科学科考队返航',
      category: 'social',
      city: '开普敦, 南非',
      lat: -33.9249,
      lng: 18.4241,
      heat: 720,
      level: 'normal',
      sentiment: 'positive',
      spread: 5200000,
      summary: '多国联合南极科考队完成为期半年的冰川微观动力学采样任务。'
    },
    {
      id: 'w008',
      title: '跨大西洋海底光缆受船只锚缆影响抢修完成',
      category: 'tech',
      city: '雷克雅未克, 冰岛',
      lat: 64.1466,
      lng: -21.9426,
      heat: 695,
      level: 'major',
      sentiment: 'neutral',
      spread: 6100000,
      summary: '北欧至北美洲主干通信网络链路恢复100%冗余带宽，网络延迟回归常态。'
    },
    {
      id: 'w009',
      title: '中东清洁氢能走廊首期工程奠基',
      category: 'policy',
      city: '迪拜, 阿联酋',
      lat: 25.2048,
      lng: 55.2708,
      heat: 654,
      level: 'normal',
      sentiment: 'positive',
      spread: 5900000,
      summary: '绿氢制备与高压管道输送一体化示范项目正式破土动工。'
    },
    {
      id: 'w010',
      title: '悉尼歌剧院数字艺术双年展开幕',
      category: 'social',
      city: '悉尼, 澳大利亚',
      lat: -33.8568,
      lng: 151.2153,
      heat: 620,
      level: 'normal',
      sentiment: 'positive',
      spread: 4800000,
      summary: 'AR与生成式艺术作品点亮悉尼海港夜空，吸引全球数十万游客线上线下互动。'
    },
    {
      id: 'w011',
      title: '北太平洋深海热液喷口发现新菌种',
      category: 'tech',
      city: '温哥华, 加拿大',
      lat: 49.2827,
      lng: -123.1207,
      heat: 588,
      level: 'normal',
      sentiment: 'positive',
      spread: 4400000,
      summary: '深海科考潜水器在3000米水深处采集到极端嗜热嗜压微生物样本。'
    },
    {
      id: 'w012',
      title: '国际航协发布可持续航空燃料年度报告',
      category: 'economy',
      city: '日内瓦, 瑞士',
      lat: 46.2044,
      lng: 6.1432,
      heat: 550,
      level: 'normal',
      sentiment: 'neutral',
      spread: 4100000,
      summary: '2026年全球SAF生物航油产能同比提升42%，但供需缺口依然存在。'
    }
  ],

  china: [
    {
      id: 'c001',
      title: '长三角低空经济示范航线网络扩容',
      category: 'policy',
      city: '上海, 中国',
      lat: 31.2304,
      lng: 121.4737,
      heat: 975,
      level: 'critical',
      sentiment: 'positive',
      spread: 14100000,
      summary: '沪苏浙皖四地首批电动垂直起降航空器（eVTOL）城际商务快线正式常态化运营。'
    },
    {
      id: 'c002',
      title: '全国算力互联调度平台接入节点突破200个',
      category: 'tech',
      city: '北京, 中国',
      lat: 39.9042,
      lng: 116.4074,
      heat: 938,
      level: 'major',
      sentiment: 'positive',
      spread: 13500000,
      summary: '东数西算国家级枢纽集群跨区域算力纳管率再创新高，大模型训练延时大幅下降。'
    },
    {
      id: 'c003',
      title: '广深港高铁日均客流创历史新高',
      category: 'economy',
      city: '广州, 中国',
      lat: 23.1291,
      lng: 113.2644,
      heat: 892,
      level: 'major',
      sentiment: 'positive',
      spread: 10200000,
      summary: '大湾区“1小时生活圈”效应显著增强，跨境通勤与商贸往来高位运行。'
    },
    {
      id: 'c004',
      title: '成渝地区双城经济圈清洁能源外送通道贯通',
      category: 'policy',
      city: '成都, 中国',
      lat: 30.5728,
      lng: 104.0668,
      heat: 845,
      level: 'normal',
      sentiment: 'positive',
      spread: 8700000,
      summary: '金沙江流域水电及风光一体化电网实现满功率向东部负荷中心输送。'
    },
    {
      id: 'c005',
      title: '国产超导量子计算机突破百比特纠错阈值',
      category: 'tech',
      city: '合肥, 中国',
      lat: 31.8206,
      lng: 117.2272,
      heat: 810,
      level: 'major',
      sentiment: 'positive',
      spread: 9100000,
      summary: '量子逻辑门保真度达到商业化应用标准，生物医药分子构象模拟取得新突破。'
    },
    {
      id: 'c006',
      title: '长江口深水航道大型LNG船舶常态化进出港',
      category: 'economy',
      city: '苏州, 中国',
      lat: 31.2989,
      lng: 120.5853,
      heat: 770,
      level: 'normal',
      sentiment: 'positive',
      spread: 6800000,
      summary: '华东天然气管网与沿海LNG接收站协同调峰能力进一步夯实。'
    },
    {
      id: 'c007',
      title: '华南沿海强对流天气预警安全响应',
      category: 'emergency',
      city: '深圳, 中国',
      lat: 22.5431,
      lng: 114.0579,
      heat: 735,
      level: 'major',
      sentiment: 'neutral',
      spread: 7400000,
      summary: '气象与应急部门联动发布短时强降水防御指引，港口及交通秩序平稳。'
    },
    {
      id: 'c008',
      title: '敦煌莫高窟数字资产全球巡展反响热烈',
      category: 'social',
      city: '兰州, 中国',
      lat: 36.0611,
      lng: 103.8343,
      heat: 699,
      level: 'normal',
      sentiment: 'positive',
      spread: 6200000,
      summary: '基于毫米级三维激光扫描的莫高窟壁画全景漫游系统访问量突破千万。'
    },
    {
      id: 'c009',
      title: '武汉光谷量子保密通信城域网扩容完毕',
      category: 'tech',
      city: '武汉, 中国',
      lat: 30.5928,
      lng: 114.3055,
      heat: 660,
      level: 'normal',
      sentiment: 'positive',
      spread: 5400000,
      summary: '金融与政务核心数据量子密钥分发链路全面覆盖东湖高新区。'
    },
    {
      id: 'c010',
      title: '杭州亚运场馆群赛后全民健身季启动',
      category: 'social',
      city: '杭州, 中国',
      lat: 30.2741,
      lng: 120.1551,
      heat: 630,
      level: 'normal',
      sentiment: 'positive',
      spread: 5100000,
      summary: '场馆低成本开放惠民方案吸引超百万市民参与智慧场馆运动。'
    },
    {
      id: 'c011',
      title: '青岛深远海风渔融合养殖平台首批收获',
      category: 'economy',
      city: '青岛, 中国',
      lat: 36.0671,
      lng: 120.3826,
      heat: 595,
      level: 'normal',
      sentiment: 'positive',
      spread: 4600000,
      summary: '离岸15海里风力发电与深水网箱养殖一体化平台实现绿色渔业丰收。'
    },
    {
      id: 'c012',
      title: '西安国际陆港中欧班列集结中心单日发车创新高',
      category: 'economy',
      city: '西安, 中国',
      lat: 34.3416,
      lng: 108.9398,
      heat: 560,
      level: 'normal',
      sentiment: 'positive',
      spread: 4300000,
      summary: '“丝路电商”冷链专列实现12天直达欧洲主要消费中心。'
    }
  ],

  // 底部事件流基础词库
  eventTemplates: [
    { label: '新增', text: '联合国安理会就区域人道主义援助达成共识' },
    { label: '更新', text: '上海低空经济航线运力较上周提升15%' },
    { label: '告警', text: '太平洋西北航道局部气象海况转差提示' },
    { label: '新增', text: '欧洲某主要央行官员发表关于降息周期讲话' },
    { label: '更新', text: '深圳算力枢纽集群能效比达到绿色一级标准' },
    { label: '告警', text: '北欧海底通信光缆例行巡检预警解除' },
    { label: '新增', text: '全球清洁能源年度投资报告发布' }
  ]
};
